---
title: "PCA Analysis"
author: "Victor Brun"
date: "2023-05-30"
output: html_document
---

# 1. Data and Packages

```{r setup, include=FALSE}

rm(list=ls()) # Cleaning the environment

# Packages
library(readxl)
library(tidyverse)
library(dplyr)
library(ggrepel)

# Data
df <- read_xlsx("./../Data/Macmon_data.xlsx")

# Renaming variables
df <- df %>% 
  rename("televisions" = "How many televisions?...171",
         "stoves" = "How many stoves?...173", 
         "flushing_toilets" = "How many flushing toilets?...175",
         "smartphones" = "How many smartphones or tablets?...177",
         "mobile_phones" = "How many mobile phones?",
         "electric_fans" = "How many electric fans?...181",
         "refrigerators" = "How many refrigerators?",
         "pigs_cows" = "How many pigs, cows and buffaloes?",
         "chickens" = "How many chickens?...187",
         "wall_material" = "Wall material",
         "roof_material" = "Roof material",
         "floor_material" = "Floor material",
         "electricity" = "Electricity",
         "boat" = "36. Do you own a boat?")

# Changing character to factors
df <- df %>% 
  mutate(wall_material = as.factor(wall_material),
         roof_material = as.factor(roof_material),
         floor_material = as.factor(floor_material),
         electricity = as.factor(electricity),
         boat = as.factor(boat))

# Survey number to match consumption data
df <- df %>% 
  mutate(Questionnaire = paste("B", `Survey number`, sep = ""))
```

# 2. Adding variables for electricity, house materials and boat

```{r}
# Check all levels of factors for each variable
summary(df$roof_material)
summary(df$wall_material)
summary(df$floor_material)
summary(df$electricity)
summary(df$boat)

# Hard roof
df <- df %>%
  mutate(roof_hard = case_when(roof_material == "Metal" ~ 1,
                               TRUE ~ 0))

# Hard walls 
df <- df %>% 
  mutate(wall_hard = case_when(wall_material %in% c("Cement", "Cement Wood", "Bamboo / Sawali Cement") ~ 1,
                               TRUE ~ 0))

# Hard floor
df <- df %>% 
  mutate(floor_hard = case_when(floor_material %in% c("Concrete") ~ 1,
                               TRUE ~ 0))


# Electricity: generator or solar (one variable each)
df <- df %>% 
  mutate(electricity_generator = case_when(electricity == "Generator" ~ 1,
                               TRUE ~ 0))

# Boat with an engine
df <- df %>% 
  mutate(boat = case_when(boat %in% c("Boat with motor (horsepower:__)", "Boat without motor (e.g., canoe) Boat with motor (horsepower:__)") ~ 1,
                          TRUE ~ 0))

# Creating smaller data set for PCA
df_pca <- df %>% select(Questionnaire, Village, televisions, stoves, smartphones, electric_fans, refrigerators, roof_hard, wall_hard, floor_hard, electricity_generator)

# NAs to 0
df_pca$televisions[is.na(df_pca$televisions)] <- 0
df_pca$stoves[is.na(df_pca$stoves)] <- 0
df_pca$smartphones[is.na(df_pca$smartphones)] <- 0
df_pca$electric_fans[is.na(df_pca$electric_fans)] <- 0
df_pca$refrigerators[is.na(df_pca$refrigerators)] <- 0

```

# 3. PCA with quantities

```{r}
# Computing PCA
pca_quant <- prcomp(df_pca[,3:11])

# Variability explained by PCA
pca.var <- pca_quant$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

barplot(pca.var.per, main="Scree Plot", xlab="Principal Component", ylab="Percent Variation") # PC1 accounts for most of the variation in the data

pca_data_quant <- data.frame(Sample=rownames(df_pca),
  X=pca_quant$x[,1],
  Y=pca_quant$x[,2])
pca_data_quant

ggplot(data=pca_data_quant, aes(x=X, y=Y, label=Sample)) +
  geom_text_repel() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("My PCA Graph")

# Ranking variables
loading_scores <- pca_quant$rotation[,1] #prcomp function calls the loading score as rotations
variable_scores <- abs(loading_scores) #absolute value function to sort based on th number's magnitude 
variable_score_ranked <- sort(variable_scores, decreasing=TRUE) #sorting from high to low
variable_score_ranked

# Plotting quantiles
index=pca_quant$x[,1]
nlab<-c(1,2,3,4,5)
newdata_quant<-mutate(df_pca, quintile=as.factor(cut(index,breaks=5,labels=nlab)))
ggplot(newdata_quant, aes(Village)) + 
  geom_bar(aes(fill = quintile), position = "fill") +
  labs(x = "Village", y = "Percentage", title = "Wealth breakdown") +
  theme_minimal()

```

# 4. PCA yes/no (presence-absence)

```{r}
# Change all values >0 to 1
df_pca_yn <- df_pca %>% 
  mutate_if(is.numeric, ~1 * (. > 0))

# Computing PCA
pca_yn <- prcomp(df_pca_yn[,3:11])

# Variability explained by PCA
pca.var <- pca_yn$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

barplot(pca.var.per, main="Scree Plot", xlab="Principal Component", ylab="Percent Variation") # PC1 accounts for most of the variation in the data

pca_data_yn <- data.frame(Sample=rownames(df_pca_yn),
  X=pca_yn$x[,1],
  Y=pca_yn$x[,2])
pca_data_yn

ggplot(data=pca_data_yn, aes(x=X, y=Y, label=Sample)) +
  geom_text() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("My PCA Graph")

# Ranking variables
loading_scores <- pca_yn$rotation[,1] #prcomp function calls the loading score as rotations
variable_scores <- abs(loading_scores) #absolute value function to sort based on th number's magnitude 
variable_score_ranked <- sort(variable_scores, decreasing=TRUE) #sorting from high to low
variable_score_ranked

# Plotting quantiles
index=pca_yn$x[,1]
nlab<-c(1,2,3,4,5)
newdata_yn<-mutate(df_pca_yn, quintile=as.factor(cut(index,breaks=5,labels=nlab)))
ggplot(newdata_yn, aes(Village)) + 
  geom_bar(aes(fill = quintile), position = "fill") +
  labs(x = "Village", y = "Percentage", title = "Wealth breakdown") +
  theme_minimal()

```

# 5. Wealth index based on house materials, generator and refrigerator

```{r}
Wealth_house <- df_pca %>% 
  rowwise() %>% 
  mutate(All_furnitures = refrigerators + roof_hard + wall_hard + floor_hard + electricity_generator)
```


# 6. Save everything

```{r}
wealth <- df %>% select(Questionnaire)
wealth$Wealth_quant <- pca_data_quant$X
wealth$Wealth_yn <- pca_data_yn$X
wealth$Wealth_house <- Wealth_house$All_furnitures
write.csv(wealth, "./../Data/Wealth.csv", row.names = F)

# Correlation between indicators
ggplot(wealth, aes(x = Wealth_quant, y = Wealth_yn)) +
  geom_point() +
  geom_smooth(method = "lm")

ggplot(wealth, aes(x = Wealth_house, y = Wealth_yn)) +
  geom_point() +
  geom_smooth(method = "lm")

ggplot(wealth, aes(x = Wealth_quant, y = Wealth_house)) +
  geom_point() +
  geom_smooth(method = "lm")
```










