---
title: "Food SFB"
author: "Victor Brun"
date: "6/11/2021"
output: html_document
---

# 1. Data and packages

```{r message=FALSE, warning=FALSE}

rm(list=ls())

library(ggplot2) ; library(tidyverse) ; library(readxl) ; library(sjPlot) ; library(sjlabelled) ; library(sjmisc)

# Consumption data
df.cons <-  read_xlsx("./../Data/Consumption_SFB.xlsx", sheet = 1)
df.hous <-  read_xlsx("./../Data/Consumption_SFB.xlsx", sheet = 2)

# Fishing data
df.fisherfolk <-  read_xlsx("./../Data/Fishing_SFB.xlsx", sheet = 6)
df.sessions <-  read_xlsx("./../Data/Fishing_SFB.xlsx", sheet = 1)

# Left join to add metadata to consumption
df.cons <- left_join(df.cons, df.hous, by = "ID_survey")

```

# 2. Origin of different products

```{r}

# Rescaling factor of food origin

df.cons$Food_origin = factor(df.cons$Food_origin, levels = c("Own product", "Gift", "Bought to local producer", "Bought from shop or middleman", "Imported from outside the village"))

# Origin of different food products depending on their type

Food_origin_type <- ggplot(data = filter(df.cons, !is.na(Food_origin))) +
  aes(x = Food_type, fill = Food_origin) +
  geom_bar() +
  scale_fill_brewer(palette="Blues") +
  labs(x = "Type of food product", y = "Number of times consumed",
       fill = "Origin of products") +
  coord_flip() +
  theme_minimal()

# Origin of different food products depending on their FAO group

Food_origin_FAO <- ggplot(data = filter(df.cons, !is.na(Food_origin))) +
  aes(x = FAO_group, fill = Food_origin) +
  geom_bar() +
  scale_fill_brewer(palette="Blues") +
  labs(x = "FAO food group", y = "Number of times consumed",
       fill = "Origin of products") +
  coord_flip() +
  theme_minimal()

Food_origin_type
Food_origin_FAO

# Origin of fish

Fish_origin <- ggplot(data = filter(df.cons, Food_type == "Fish", !is.na(Food_origin),
                                    !is.na(Barangay))) +
  aes(x = Barangay, fill = Food_origin) +
  geom_bar(position="Fill") +
  scale_fill_brewer(palette="Set3") +
  labs(x = "Origin of fish per village", y = "",
       fill = "Origin of fish") +
  theme_minimal()
Fish_origin

# Food consumed per village (FAO group)

ggplot(data = filter(df.cons, !is.na(Barangay))) +
  aes(x = Barangay, fill = Food_type) +
  geom_bar(position="fill") +
  scale_fill_brewer(palette="Set3") +
  labs(x = "FAO food group", y = "Number of times consumed",
       fill = "Origin of products") +
  theme_minimal()

# Destination of fish caught

ggplot(data = filter(df.fisherfolk, !is.na(Dest_t1))) +
  aes(x = Barangay, fill = Dest_t1) +
  geom_bar(position="fill") +
  scale_fill_brewer(palette="Set3") +
  labs(x = "Destination", y = "",
       fill = "Destination of products per barangay") +
  theme_minimal()


```

# 3. Diversity of fishing gears and habitats targeted by fishers

```{r}

# Pivoting longer so that all gears surveyed appear
gears_long = df.fisherfolk %>%
  select(Barangay, Gear_1, Gear_2, Gear_3) %>%
  pivot_longer(c(Gear_1, Gear_2, Gear_3)) %>%
  filter(!is.na(value))
colnames(gears_long) <- c("Village", "Gear_number", "Gear")

# Plotting the diversity of gears per village
gears_village <- ggplot(data = filter(gears_long, !Gear %in% c("Blast", "Cyanide"))) +
  aes(x = Village, fill = Gear) +
  geom_bar(position = "fill") +
  scale_fill_brewer(palette="Set3") +
  theme_minimal()
gears_village

# Pivoting longer so that all habitats targeted surveyed appear
habitats_long = df.fisherfolk %>%
  select(Barangay, Hab_1, Hab_2, Hab_3) %>%
  pivot_longer(c(Hab_1, Hab_2, Hab_3)) %>%
  filter(!is.na(value))
colnames(habitats_long) <- c("Village", "Habitat_number", "Habitat")

# Batas
habitats_Batas <- habitats_long %>%
  filter(Village == "Batas")
habitats_Batas <- table(habitats_Batas$Habitat)
habitats_Batas <- data.frame(habitats_Batas)

ggplot(data = filter(habitats_Batas, Var1 != "Mangrove", !is.na(Var1))) +
  aes(x = "", y = Freq, fill = Var1) +
  geom_bar(stat="identity", position = "dodge") +
  coord_polar() +
  scale_fill_brewer(palette="Set1") +
  labs(title="Batas") +
  theme_void()

# Depla
habitats_Depla <- habitats_long %>%
  filter(Village == "Depla")
habitats_Depla <- table(habitats_Depla$Habitat)
habitats_Depla <- data.frame(habitats_Depla)

ggplot(data = filter(habitats_Depla, Var1 != "Mangrove", !is.na(Var1))) +
  aes(x = "", y = Freq, fill = Var1) +
  geom_bar(stat="identity", position = "dodge") +
  coord_polar() +
  scale_fill_brewer(palette="Set1") +
  labs(title="Depla") +
  theme_void()

# Mabini
habitats_Mabini <- habitats_long %>%
  filter(Village == "Mabini")
habitats_Mabini <- table(habitats_Mabini$Habitat)
habitats_Mabini <- data.frame(habitats_Mabini)

ggplot(data = filter(habitats_Mabini, Var1 != "Mangrove", !is.na(Var1))) +
  aes(x = "", y = Freq, fill = Var1) +
  geom_bar(stat="identity", position = "dodge") +
  coord_polar() +
  scale_fill_brewer(palette="Set1") +
  labs(title="Mabini") +
  theme_void()

# Sandoval
habitats_Sandoval <- habitats_long %>%
  filter(Village == "Sandoval")
habitats_Sandoval <- table(habitats_Sandoval$Habitat)
habitats_Sandoval <- data.frame(habitats_Sandoval)

ggplot(data = filter(habitats_Sandoval, Var1 != "Mangrove", !is.na(Var1))) +
  aes(x = "", y = Freq, fill = Var1) +
  geom_bar(stat="identity", position = "dodge") +
  coord_polar() +
  scale_fill_brewer(palette="Set1") +
  labs(title="Sandoval") +
  theme_void()

# Silanga
habitats_Silanga <- habitats_long %>%
  filter(Village == "Silanga")
habitats_Silanga <- table(habitats_Silanga$Habitat)
habitats_Silanga <- data.frame(habitats_Silanga)

ggplot(data = filter(habitats_Silanga, Var1 != "Mangrove", !is.na(Var1))) +
  aes(x = "", y = Freq, fill = Var1) +
  geom_bar(stat="identity", position = "dodge") +
  coord_polar() +
  scale_fill_brewer(palette="Set1") +
  labs(title="Silanga") +
  theme_void()

```

# 4. Fishing effort and yields

```{r}

# Number of fishing households

fishing_households <- df.hous %>%
  group_by(Barangay) %>%
  summarise(fishing_households = mean(Fisherman, na.rm=TRUE))

# Cumulative fishing effort

effort <- df.fisherfolk %>%
  group_by(Barangay) %>%
  summarise(effort = sum(as.numeric(as.character(Fishing_days))))

# Linking both variables and plotting

fishing_effort <- fishing_households %>%
  mutate(effort = effort$effort)
rm(effort, fishing_households)

ggplot(data = fishing_effort) +
  aes(x = Barangay, y = effort, size = fishing_households) +
  geom_point() +
  theme_minimal()

```

# 5. CPUE per village

```{r}
df.sessions$CPUE <- as.numeric(as.character(df.sessions$Capture_kg))/as.numeric(as.character(df.sessions$Time_fish))

ggplot(data = filter(df.sessions, !is.na(CPUE), Habitat_type == "Coral reef",
                     Habitat_1 %in% c("Batas", "Depla", "Mabini", "Sandoval", "Silanga"),
                     Gear == "Hook and line")) +
  aes(x = Habitat_1, y = CPUE) +
  geom_boxplot() +
  geom_jitter(width=0.10, alpha=0.5) +
  labs(x = "CPUE per village", y = "Hook and line CPUE (kg/hour)") +
  theme_minimal()

hook <- filter(df.sessions, !is.na(CPUE), Habitat_type == "Coral reef",
                     Habitat_1 %in% c("Batas", "Depla", "Mabini", "Sandoval", "Silanga"),
                     Gear == "Hook and line", Fisherman != "JOHTAGSA")

tapply(hook$CPUE, hook$Habitat_1, mean, na.rm=TRUE)

aov.res = aov(hook$CPUE ~ hook$Habitat_1)
summary(aov.res)

pairwise.t.test(hook$CPUE, hook$Habitat_1)

glm_cpue <- glm(CPUE ~ Habitat_1, data = hook)
plot_model(glm_cpue, show.values = TRUE, value.offset = .4,
           title = "CPUE depending on different fishing spots (base = Batas)")


# Locality of fishing

df.fisherfolk <- df.fisherfolk %>%
  mutate(Local_fisher = as.factor(ifelse(Barangay == Ground_1, 1, 0)))

ggplot(data = df.fisherfolk) +
  aes(x = Barangay, fill = Local_fisher) +
  geom_bar() +
  scale_fill_brewer(palette="Set3") +
  theme_minimal()

```


# 6. Products consumption per village

```{r}

df.cons$Food_quantity <- as.numeric(as.character(df.cons$Food_quantity))
df.cons$House_meal <- as.numeric(as.character(df.cons$House_meal))

# Computing total fish, veg and meat consumption per household
fish_consumed <- df.cons %>%
  filter(Food_type %in% c("Fish", "Dry fish")) %>%
  group_by(ID_survey) %>%
  summarise(Fish_quantity = sum(Food_quantity))
veg_consumed <- df.cons %>%
  filter(Food_type %in% c("Vegetables")) %>%
  group_by(ID_survey) %>%
  summarise(Veg_quantity = sum(Food_quantity))
meat_consumed <- df.cons %>%
  filter(Food_type %in% c("Meat")) %>%
  group_by(ID_survey) %>%
  summarise(Meat_quantity = sum(Food_quantity))

# Adding info to households
df.hous <- df.hous %>%
  left_join(fish_consumed) %>%
  left_join(veg_consumed) %>%
  left_join(meat_consumed)

# Transforming NA to 0
df.hous$Fish_quantity[is.na(df.hous$Fish_quantity)] = 0
df.hous$Fish_quantity = (df.hous$Fish_quantity/(df.hous$Nb_toth*df.hous$House_meal))*3*365
df.hous$Meat_quantity[is.na(df.hous$Meat_quantity)] = 0
df.hous$Meat_quantity = (df.hous$Meat_quantity/(df.hous$Nb_toth*df.hous$House_meal))*3*365
df.hous$Veg_quantity[is.na(df.hous$Veg_quantity)] = 0
df.hous$Veg_quantity = (df.hous$Veg_quantity/(df.hous$Nb_toth*df.hous$House_meal))*3*365


# ANOVA
aov_fish = aov(Fish_quantity ~ Barangay, data = df.hous)
summary(aov_fish)

# GLM
glm_fish <- glm(Fish_quantity ~ Barangay + Sex, data = df.hous)
plot_model(glm_fish, show.values = TRUE, value.offset = .4,
           title = "Fish consumption depending on village surveyed")

# Boxplot representing the consumption of fish per village
ggplot(data = df.hous) +
  aes(x = Barangay, y = Fish_quantity) +
  geom_boxplot() +
  ylim(0,250) +
  geom_jitter(width=0.10, alpha=0.5) +
  labs(x = "Per capita fish consumption per village", y = "Per capita consumption (kg/pers*year)") +
  theme_minimal()

```






