---
title: "Palawan BFAR data"
author: "Victor Brun"
date: "2024-02-17"
output: html_document
---

# Data and packages
```{r}
rm(list=ls())

library(readxl)
library(tidyverse)
library(ggplot2)
library(fishualize)

# Data
df <- read.csv("./../Data/Palawan_BFAR_Data.csv", sep = ";")

# Rename columns with years
colnames(df) <- c("Location", "Species", "2002":"2023")

# Add reef or pelagic
df$Habitat <- df$Species %>%
  fct_recode(
    NULL = "Acetes (Alamang)",
    "Pelagic/\nSoft bottom" = "Anchovies (Dilis)",
    "Pelagic/\nSoft bottom" = "Bali sardinella (Tamban)",
    "Pelagic/\nSoft bottom" = "Big-eyed scad (Matangbaka)",
    "Pelagic/\nSoft bottom" = "Bigeye tuna (Tambakol/ Bariles)",
    NULL = "Blue crab (Alimasag)",
    "Reef" = "Caesio (Dalagang-bukid)",
    "Reef" = "Cavalla (Talakitok)",
    "Pelagic/\nSoft bottom" = "Crevalle (Salay-salay)",
    "Pelagic/\nSoft bottom" = "Eastern little tuna (Bonito)",
    "Pelagic/\nSoft bottom" = "Fimbriated sardines (Tunsoy)",
    "Pelagic/\nSoft bottom" = "Flying fish (Bolador)",
    "Pelagic/\nSoft bottom" = "Frigate tuna (Tulingan)",
    "Reef" = "Goatfish (Saramulyete)",
    "Reef" = "Grouper (Lapu-lapu)",
    "Pelagic/\nSoft bottom" = "Hairtail (Espada)",
    "Pelagic/\nSoft bottom" = "Indian mackerel (Alumahan)",
    "Pelagic/\nSoft bottom" = "Indo-pacific mackerel (Hasa-hasa)",
    "Reef" = "Mullet (Kapak)",
    NULL = "Others",
    "Reef" = "Parrot fish (Loro)",
    "Reef" = "Porgies (Pargo)",
    "Pelagic/\nSoft bottom" = "Round herring (Tulis)",
    "Pelagic/\nSoft bottom" = "Roundscad (Galunggong)",
    "Reef" = "Siganid (Samaral)",
    "Pelagic/\nSoft bottom" = "Skipjack (Gulyasan)",
    "Pelagic/\nSoft bottom" = "Slipmouth (Sapsap)",
    "Reef" = "Snapper (Maya-maya)",
    "Pelagic/\nSoft bottom" = "Spanish mackerel (Tanigue)",
    NULL = "Squid (Pusit)",
    "Pelagic/\nSoft bottom" = "Threadfin bream (Bisugo)",
    "Pelagic/\nSoft bottom" = "Yellowfin tuna (Tambakol/Bariles)")

# Pivot longer for tidyness
df <- df %>% 
  pivot_longer(cols = c("2002":"2023"), names_to = "Year", values_to = "Catch (mt)")

# Theme perso
theme_perso <- function(){
  theme_bw() +
    theme(text = element_text(family = "Helvetica Light"),
          axis.line.x = element_line(color="black"), 
          axis.line.y = element_line(color="black"),
          panel.border = element_blank(),
          panel.grid.major.x = element_blank(),                                          
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),  
          plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), units = , "cm"),
          legend.key = element_blank(),
          legend.background = element_rect(color = "black", 
                                           fill = "transparent", 
                                           linewidth = 2, linetype = "blank"))
}

```

# Dataviz

```{r}
# Total catch per habitat
df %>%
  filter(!is.na(`Catch (mt)`), !is.na(Habitat)) %>% 
  group_by(Habitat, Year) %>% 
  summarize(Catch = sum(`Catch (mt)`), .groups = "drop") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  ggplot(aes(x = Year, y = Catch, col = Habitat, group = Habitat)) +
  geom_point() +
  geom_line() +
  scale_color_fish_d(option = "Alosa_fallax") +
  labs(x = "", y = "Total landed catch (mt)", col = "") +
  theme_perso() +
  theme(legend.position = c(0.8, 0.8)) +
  scale_x_continuous(breaks=seq(2002, 2023, 3))
ggsave("./../Output/Catch_Palawan.png", height = 3, width = 4)

# Total catch per reef species for three time periods
df %>%
  filter(!is.na(`Catch (mt)`), !is.na(Habitat), Habitat == "Reef") %>% 
  mutate(Period = case_when(Year <= 2008 ~ "2002-2008",
                            Year > 2008 & Year <= 2015 ~ "2009-2016",
                            Year > 2015 ~ "2017 - 2023")) %>% 
  group_by(Species, Period) %>% 
  summarize(Catch = mean(`Catch (mt)`), .groups = "drop") %>% 
  ggplot(aes(x = Period, y = Catch, fill = Species)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_perso()

# Total catch per pelagic and soft bottom species for three time periods
df %>%
  filter(!is.na(`Catch (mt)`), !is.na(Habitat), Habitat == "Pelagic/\nSoft bottom") %>% 
  mutate(Period = case_when(Year <= 2008 ~ "2002-2008",
                            Year > 2008 & Year <= 2015 ~ "2009-2016",
                            Year > 2015 ~ "2017 - 2023")) %>% 
  group_by(Species, Period) %>% 
  summarize(Catch = mean(`Catch (mt)`), .groups = "drop") %>% 
  ggplot(aes(x = Period, y = Catch, fill = Species)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_perso()

```

